version: '3.8' #Versi칩n de sintaxis de Docker Compose
services: #Se define los 3 m칩dulos de la aplicaci칩n
  backend: # Contenedor de la API
    build: ./backend # Indicacion para buscar la carpeta ./backend y seguir las instrucciones del mismo
    ports:
      - "8080:8080" #Conexion entre puertos del pc y la p치gina
    environment: #Creedenciales para la BD
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: scanner_db
      DB_HOST: db
    networks:
      - go-network
    depends_on: #Es una condicion para que no inicie el contenedor sin que la BD este lista
      db:
        condition: service_healthy

  frontend:
    build: ./frontend #Busca la carpeta frontend
    ports:
      - "3000:80" #Conecta al puerto 3000 de la pc al 80 del contenedor
    networks:
      - go-network
    depends_on: #No inicies si el backend no esta listo
      - backend

  db:
    image: mysql:8.0
    ports:
    - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: scanner_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - go-network
    # Corrected indentation for the healthcheck block
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  go-network:
    driver: bridge

volumes:
  db_data: